---
title: the Logbook
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
baseurl: ''
google_analytics: 
host: 0.0.0.0
maps_api: AIzaSyA7XGsDS5WftXFgNiuIouzMy20aH9XyT3w
description: 
url: ''
twitter_username: 
default_img: 
include:
- _categories
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
markdown: kramdown
permalink: "/entries/:year-:month-:day-:title/"
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
- jekyll-archives
- jekyll-redirect-from
jekyll-archives:
  enabled:
  - tags
  - categories
  - day
  layouts:
    tag: archive
    category: archive
    day: archive_day
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/days/:year-:month-:day/"
    tag: "/people/:name/"
    category: "/place/:name/"
